--초기 권한 셋팅
insert into tb_role values('R01','사용자');
insert into tb_role values('R00','관리자');

--초기 사용자 셋팅
INSERT INTO `tb_usr` (`usr_id`, `gender`, `rrn`, `tel_num1`, `tel_num2`, `tel_num3`, `usr_nm`, `usr_pw`) VALUES ('user01', 'M', '930101', '010', '0000', '0000', '사용자1', '$2a$10$gTliuJ/ksWYY05MtCtugCuKSd.9..9pH54aDn3EIzy.HfvomD6owG');

--초기 사용자 권한 매핑
INSERT INTO `tb_usr_role` (`usr_id`, `role_cd`) VALUES ('user01', 'R01');

--초기 카테고리 셋팅
INSERT INTO `tb_category` (`category_seq`, `category_nm`, `reg_date`, `use_yn`, `user_id`) VALUES (1, 'IT', '2021-12-18 22:03:53', 'Y', "user01");

--초기 게시물 셋팅
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( 1,'게시물내용1', '2021-12-18 22:08:36', '2021-12-18 22:08:36', '게시물1', 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');
INSERT INTO `bbs_entity` (`bbs_seq`, `contents`, `mod_date`, `reg_date`, `title`, `use_yn`, `category_seq`, `user_id`) VALUES ( (select max(z.bbs_seq) + 1 from bbs_entity z),concat('게시물내용',(select max(z.bbs_seq) + 1 from bbs_entity z)), sysdate(), sysdate(), concat('게시물',(select max(z.bbs_seq) + 1 from bbs_entity z)), 'Y', 1, 'user01');